; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev                     ; Bo mạch: "ESP32 Dev Module"
framework = arduino

upload_speed = 921600                ; Upload Speed
board_build.f_cpu = 240000000L       ; CPU Frequency 240MHz
board_build.f_flash = 80000000L      ; Flash Frequency 80MHz
board_build.flash_mode = qio         ; Flash Mode QIO
board_upload.flash_size = 4MB        ; Flash Size 4MB
board_build.partitions = default.csv ; Default 4MB with spiffs

build_flags =
	-DCORE_DEBUG_LEVEL=0             ; 0=None ... 5=Verbose
	-DARDUINO_RUNNING_CORE=1         ; Arduino Runs On: Core 1
	-DARDUINO_EVENT_RUNNING_CORE=1   ; Events Run On: Core 1
	; -DBOARD_HAS_PSRAM              ; Bật PSRAM nếu board hỗ trợ

upload_port = /dev/tty.usbserial-0001
monitor_port = /dev/tty.usbserial-0001
monitor_speed = 115200
